project:
  type: website

website:
  title: "Climate and Wildlife: Understanding the Ecosystems of Southeastern Utah"
  navbar:
    logo: "utah.png"
    search: true
    left:
      - href: index.ipynb
        text: Home
    tools:
      - icon: github
        text: GitHub Repository
        url: https://github.com/bella20000605/NABR

format:
  html:
    theme:
      light: United
      dark: darkly
    css: theme.scss
    toc: true
    debug: true
