project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



